### ISSUE TITLE
The $view could not be loaded

### ISSUE THREAD

**Issue by MaluNoPeleke** [mauricerenck/indieConnector#1]
After installing the plugin (1.2.1) I get an error "The $view could not be loaded" when trying to accessing the panel page:

> Error: The $view could not be loaded
>     at Object.request (index.js:1)
>     at async Object.go (index.js:1)
> error @ index.js:1
> (anonymous) @ vendor.js:6
> _s.dispatch @ vendor.js:12
> dispatch @ vendor.js:6
> window.onunhandledrejection @ index.js:1

> index.js:1 GET https://dev.domain.tld/panel/webmentions?language=de 500
> request @ index.js:1
> go @ index.js:1
> t.$go.window.panel.$go @ index.js:1
> onClick @ index.js:1
> Vt @ vendor.js:6
> n @ vendor.js:6
> i._wrapper @ vendor.js:6
> index.js:1 Error: The $view could not be loaded
>     at Object.request (index.js:1)
>     at async Object.go (index.js:1)
> error @ index.js:1
> (anonymous) @ vendor.js:6
> _s.dispatch @ vendor.js:12
> dispatch @ vendor.js:6
> window.onunhandledrejection @ index.js:1

**Comment by mauricerenck** [comment]
Okay, I guess I have to hire you for the QA position! ;) 

I would guess there may be something wrong with the database. Is the file .sqlite file created?

**Comment by MaluNoPeleke** [comment]
I am just migrating my personal blog from Ghost CMS to Kirby CMS to learn something new and to have more flexibility and as I have not a lot of experience and I am also not a developer I maybe do things differently than it was thought of by developers ;)

I cannot find any .sqlite file. Should it be in the root directory or somewhere else?

**Comment by mauricerenck** [comment]
That's a good approach to learn something new, I appreciate your feedback :)

Have a look here: https://github.com/mauricerenck/indieConnector/blob/main/docs/setup.md
In order to use the panel view, you have to enable stats and set a path for the database file. This could be in `.sqilte` as suggested or in your content folder. The important part is: this folder has to exist as the plugin won't create it and then will fail writing the file.

I am working on a solution to somehow give more useful feedback in the panel. But currently if something in the php part of the plugin throws an error, kirby will show the view error you've seen. You could look into the browser console and should see a request that failed with some error message in the response.

**Comment by MaluNoPeleke** [comment]
If have set that already to this in the config

```
    'mauricerenck.indieConnector.stats' => true,
    'mauricerenck.indieConnector.sqlitePath' => '.logs/',
```

but I still get the error and sqlite is supported by my hoster. Is there any other way to debug it further?

**Comment by mauricerenck** [comment]
You should be able to set the endpoint and secret here: https://webmention.io/settings/webhooks

The error 404 ist correct. The enpoint is a POST endpoint, which means you cannot open in directly in the browser (which is a GET call), you have to use a POST-Call (like when sending a form) for that. Also some header information has to be included when calling the endpoint, otherwise it will return the 404 error.

If you have access you could have a look at the error oder access logs of your hosting package. This might include further details on why the error occures. Did you enable debug mode for kirby?

**Comment by MaluNoPeleke** [comment]
Maybe my first webmention is missing. Could you do me a favor and try it out here?
https://dev.peleke.de/de/blog/umstieg-von-ghost-cms-auf-kirby-cms

**Comment by mauricerenck** [comment]
I tried to send a webmention via curl, let me know if something arrived on your end. Also please update to the latest version, where I fixed a nasty bug. 

If you look into the .logs folder, is there a indieConnector.sqlite file?

**Comment by MaluNoPeleke** [comment]
Thanks, but I cannot see anything. These are the only mentions I received so far but they don't show up (only visible via webmention.io):
![image](https://user-images.githubusercontent.com/1446541/146656249-119f75d0-642b-4af3-b074-71b8c56384b4.png)
There is also no indieConnector.sqlite file created, only a simplestats.sqlite (from the SimpleStats plugin).
Is something wrong with the config? 

`'mauricerenck.indieConnector.sqlitePath' => '.logs/'`

![image](https://user-images.githubusercontent.com/1446541/146656280-2c372994-8022-4657-9f88-66bb392f5f73.png)

**Comment by mauricerenck** [comment]
I just liked you post, if you have the latest version of the indieConnector it should be visible in the backend. Please be aware that the plugin currently only works with webmention.io webhooks, so only new webmentions will be shown in the stats, no webmentions existing before. I plan to implement an additional way to retreive webmentions, then it will be possible to also get older ones.

**Comment by MaluNoPeleke** [comment]
Thanks a lot, it works 🙂
