### ISSUE TITLE
Getting ”Could not sent webmention” message when sending a test mention

### ISSUE THREAD

**Issue by JasonNeel** [mauricerenck/indieConnector#12]
Hi, 

I'm having trouble getting the send test mention endpoint to work. I've installed the indieConnector plugin to my site. I've included a secret key in my site's config file, set up my account on webmention.io and added the necessary tags to [my site's `<head>`](https://jasonneel.com). Yet, when I try to access the built-in function to send myself a test webmention, using the secret in my config file, the message I receive is "Could not sent webmention." I've tried changing my secret, thinking there may be an issue with the value I'm using. I'm just not sure what I'm doing wrong. Do you have any suggestions on what I can try?

Thanks,
Jason

**Comment by mauricerenck** [comment]
Hi Jason,

unfortunately this method does not work reliable. I am working on another solution for this. An upcoming release will hopefully also make it possible to use the plugin without webmention.io.

In the meantime you could send me a public url of a page where I can send a webmention to, that should do it.

**Comment by JasonNeel** [comment]
Yes! I do see it in my webmention.io dashboard. So that seems to be working now. 

Should this also show up in the Komments section of my site's panel as well? Or am I not understanding that part correctly?

**Comment by mauricerenck** [comment]
Perfect!
No, you won't be able to see it. The initial setup of webmention.io is a bit confusing. 
You first have to receive a webmention on webmention.io, to be able to set the secret and url for the webhhook. Once you set them, a webhook will be triggered for all new webmentions and then IndieConnector will receive them and hand them to the komments plugin. So unfortunately the first webmention will never make it to your site.

Right now I am working on "native" webmentions, so that IndieConnector doesn't rely on webmention.io, this will make everything easier, because you don't have to setup anything if you don't want to use webmention.io.

**Comment by JasonNeel** [comment]
I think I understand now. Thanks, @mauricerenck! I'm excited to have this set up and to be able to start experimenting with it all.
